### ISSUE TITLE
integration 

### ISSUE THREAD

**Issue by hamzazzi** [egguy/EnergEasyAPI#1]
the integration dont work for me

**Comment by egguy** [comment]
Hello,

Do you have more information about the problem ?
There's some minor details not pushed to the new version of the API, but it should work ATM (except for the auto relog).

**Comment by egguy** [comment]
And this is only the API, used by the component for HA. I'm still ironing out some minor defect for the HomeAssistant integration.
Are you interested to test the integration ?
There's only the support for  
  - Blind (fully functional)
  - Thermostat (Partially working)
  - WaterHeater (not working because Rexel say this device doesn't exist event if it registered with the box and won't correct the problem)

**Comment by hamzazzi** [comment]
Bonjour Étienne, je suis novice sur HA, peux-tu m'aider à intégrer energeasy connect stp ?

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by hamzazzi** [comment]
yes i want to 👍

**Comment by egguy** [comment]
@hamzazzi The integration has been replaced by the native overkiz API, this work well, and I work on this integration.
You can find the integration natively in HA now.
